name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: home-server

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get to work dir
        run: cd $GITHUB_WORKSPACE

      # Fix permissions for the target directory before rsync
      - name: Ensure target directory exists with correct permissions
        run: |
          mkdir -p /home/dvishal485/TeamPortal/nix-backend
          sudo chown -R $USER:$USER /home/dvishal485/TeamPortal/nix-backend
          chmod -R 755 /home/dvishal485/TeamPortal/nix-backend

      # Copy source code to NEW target dir with permission fixes
      - name: Copy source code to target dir
        run: rsync -avz --no-group --chmod=D755,F644 $GITHUB_WORKSPACE/ /home/dvishal485/TeamPortal/nix-backend/

      - name: Get to target dir
        run: cd /home/dvishal485/TeamPortal/nix-backend

      - name: Install dependencies
        run: |
          cd /home/dvishal485/TeamPortal/nix-backend
          npm i

      # Updated PM2 restart command with correct process name
      - name: Deploy to web
        run: |
          cd /home/dvishal485/TeamPortal/nix-backend
          pm2 restart nix-shell-env
