name: Deploy Backend to Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy: 
    runs-on: home-server

    steps:
      # latest code from your repository
      - name: 1. Checkout Repository Code
        uses: actions/checkout@v4
        with:
          submodules: true

      # the new code to the live application directory.
      - name: 2. Sync Files to Live Directory
        run: rsync -avz $GITHUB_WORKSPACE/ /home/dvishal485/TeamPortal/nix-backend/

      # install dependencies.
      - name: 3. Install NPM Dependencies
        working-directory: /home/dvishal485/TeamPortal/nix-backend
        run: npm install

      # restart the application.
      - name: 4. Restart Application with PM2
        working-directory: /home/dvishal485/TeamPortal/nix-backend
        run: /root/.local/share/devbox/global/default/.devbox/nix/profile/default/bin/pm2 restart nix-shell-env

